### ISSUE TITLE
check-out without credentials, but check-in needs authentikation

### ISSUE THREAD

**Issue by gurucubano** [adelton/mod_authnz_pam#18]
Hi,

I've configured the PAM authentication via SSSD to our Active Directory, which works fine and asks on ```svn co http://svn-server.foo.bar/svn/``` for the domain credentials.
Is there a way to configure, that checkout works without credentials and for check-in you need the credentials?

Thanks

**Comment by adelton** [comment]
The https://svnbook.red-bean.com/en/1.7/svn.serverconfig.httpd.html#svn.serverconfig.httpd.authz.blanket has an example which uses
```
  # Authorization: Authenticated users only for non-read-only
  #                (write) operations; allow anonymous reads
  <LimitExcept GET PROPFIND OPTIONS REPORT>
    Require valid-user
  </LimitExcept>
```
to achieve what you describe.

Doesn't it fit your situation?

**Comment by gurucubano** [comment]
Maybe mine has a mistake, it asks for credentials on check-out:
```
LoadModule dav_svn_module     modules/mod_dav_svn.so
LoadModule authz_svn_module   modules/mod_authz_svn.so
# LogLevel debug

<Location /svn>
  DAV svn
  SVNPath /appdata/svn/repository
  SVNIndexXSLT "/svnindex.xsl"

  AuthzSVNAccessFile /appdata/svn/svn-access-file

  <LimitExcept GET PROPFIND OPTIONS REPORT>
    # Satisfy All
    Require valid-user
  </LimitExcept>

  AuthType Basic
  AuthName "EMEA subversion"
  AuthBasicProvider PAM
  AuthPAMService svn
  Require pam-account svn
</Location>
```
Thanks for your hints.

**Comment by adelton** [comment]
You have that `Require pam-account svn` outside of that `<LimitExcept>` block.

**Comment by gurucubano** [comment]
Yes :-(
I saw it right now also. Thanks for your help.

**Comment by adelton** [comment]
Glad you got it resolved.
