### ISSUE TITLE
Compile error on SLES 15.4

### ISSUE THREAD

**Issue by yandamfin** [adelton/mod_authnz_pam#19]
Hi,

Here is the rror I get when trying to compile this mocule on SLES 15.4:
```
-----------------------------------------------
mod_authnz_pam-1.2.3 # apxs -i -a -c mod_authnz_pam.c -lpam -Wall -pedantic
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -Wall -DLDAP_DEPRECATED  -DLINUX -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1 -I/usr/include  -c -o mod_authnz_pam.lo mod_authnz_pam.c && touch mod_authnz_pam.slo
mod_authnz_pam.c:18:10: fatal error: security/pam_appl.h: No such file or directory
 #include <security/pam_appl.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
apxs:Error: Command failed with rc=65536
.
----------------------------------------------
```

I have been searching the internet for days to resolve this but found almost nothing and nothing relevant.

Thank you for you feedback and assistance.

Best regards

**Comment by adelton** [comment]
I'd guess the `pam-devel` that we have in BuildRequires should work on SLESes as well -- can you try that?

**Comment by yandamfin** [comment]
Hi Adleton,

Thank you: it did work with pam-devel.

Out of curiosity, what are you referring to when talking about "BuildRequires"?

I could not find anything related to this in the README, LICENSE, etc. files.

Thank you.

Best regards,

**Comment by adelton** [comment]
I'm talking about the rpm `.spec` file: https://github.com/adelton/mod_authnz_pam/blob/master/mod_authnz_pam.spec#L18

Granted, it is for Fedora / RHEL / derivatives so it would require some tweaks for SLES, but luckily the `pam-devel` package seems to exist there as well.
